package com.example.fabricarestcrudexample240.repositories

import com.example.fabricarestcrudexample240.entities.ProductEntity
import org.springframework.data.repository.reactive.ReactiveCrudRepository

interface ProductRepository: ReactiveCrudRepository<ProductEntity, Long>